sudo: required
services:
  - docker

before_install:
  - docker build -t dponnada/docker-react -f Dockerfile.dev .

  script:
    - docker run dponnada/docker-react npm run test -- --coverage 

    branches:
        only:
            - master