language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t dponnada/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dponnada/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket: "elasticbeanstalk-us-east-1-927729158917"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
