language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t dponnada/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dponnada/docker-react npm run test
